# Rebuild the geometric app icon using Windows drawing primitives.
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing
$hubBitmap = [System.Drawing.Bitmap]::new(256, 256)
$hubGraphics = [System.Drawing.Graphics]::FromImage($hubBitmap)
$hubGraphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
$hubShape = [System.Drawing.Drawing2D.GraphicsPath]::new()
$hubShape.AddArc(8, 8, 88, 88, 180, 90)
$hubShape.AddArc(160, 8, 88, 88, 270, 90)
$hubShape.AddArc(160, 160, 88, 88, 0, 90)
$hubShape.AddArc(8, 160, 88, 88, 90, 90)
$hubShape.CloseFigure()
$hubBrush = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#0C1B2A'))
$hubGraphics.FillPath($hubBrush, $hubShape)
$hubAccent = [System.Drawing.SolidBrush]::new([System.Drawing.ColorTranslator]::FromHtml('#94EDF5'))
$hubRing = [System.Drawing.Pen]::new([System.Drawing.ColorTranslator]::FromHtml('#42B6CC'), 6)
$hubGraphics.DrawArc($hubRing, 32, 32, 192, 192, 15, 135)
$hubGraphics.DrawArc($hubRing, 32, 32, 192, 192, 195, 135)
$hubGraphics.FillRectangle($hubAccent, 82, 78, 14, 100)
$hubGraphics.FillRectangle($hubAccent, 160, 78, 14, 100)
$hubGraphics.FillRectangle($hubAccent, 87, 121, 82, 14)
$hubPng = [System.IO.MemoryStream]::new()
$hubBitmap.Save($hubPng, [System.Drawing.Imaging.ImageFormat]::Png)
$hubFile = [System.IO.File]::Create((Join-Path $PSScriptRoot 'aihub.ico'))
$hubWriter = [System.IO.BinaryWriter]::new($hubFile)
$hubWriter.Write([UInt16]0); $hubWriter.Write([UInt16]1); $hubWriter.Write([UInt16]1)
$hubWriter.Write([byte]0); $hubWriter.Write([byte]0); $hubWriter.Write([byte]0); $hubWriter.Write([byte]0)
$hubWriter.Write([UInt16]1); $hubWriter.Write([UInt16]32)
$hubWriter.Write([UInt32]$hubPng.Length); $hubWriter.Write([UInt32]22)
$hubWriter.Write($hubPng.ToArray())
$hubWriter.Dispose(); $hubPng.Dispose(); $hubBrush.Dispose(); $hubAccent.Dispose(); $hubRing.Dispose(); $hubShape.Dispose(); $hubGraphics.Dispose(); $hubBitmap.Dispose()
